services:
  api:
    build:
      context: ./app
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      MARIA_HOST: ${MARIA_HOST}
      MARIA_PORT: ${MARIA_PORT}
      MARIA_USER: ${MARIA_USER}
      MARIA_PASSWORD: ${MARIA_PASSWORD}
      MARIA_DATABASE: ${MARIA_DATABASE}
      TOKEN_SECRET: ${TOKEN_SECRET}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}

    depends_on:
      - db
    restart: on-failure
    command: npm start
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIA_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIA_DATABASE}
      MYSQL_USER: ${MARIA_USER}
      MYSQL_PASSWORD: ${MARIA_PASSWORD}
    ports:
      - "${MARIA_PORT}:3306"
    volumes:
      - ./db:/var/lib/mysql
